import type { Metadata,Viewport } from 'next'
import { Providers } from '@/redux/providers'
import './globals.css'
import { Header } from '@/components/Header'
import BackGround from '@/components/BackGround'
import RemoveBG from '@/components/RemoveBG'



export const metadata: Metadata = {
  title: 'Aditya Aryan',
  description: 'Generated by Aditya Aryan',

}
export const viewport: Viewport={
  width:"device-width",
  userScalable:false,
  initialScale:1
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <Providers>
        <body className='bg-zinc-950 h-screen text-white overflow-hidden flex flex-col'>
          <Header />
          <div className="flex-1 h-full"
        >
            <BackGround />
            {children}
            <RemoveBG />
          </div>
          
        </body>
      </Providers>
    </html>
  )
}
